### ISSUE TITLE
这么好的东西为什么不直接加进xray命令行呢

### ISSUE THREAD

**Issue by Fangliding** [XTLS/RealiTLScanner#1]
就像生成x2551⑨ key一样

**Comment by yuhan6665** [comment]
是可以加 core
不加的考虑是 1 这个工具可能进一步扩展 不影响 core 变大 2 安全考虑 扫描功能比较敏感 3 运行环境不同 建议本地运行

**Comment by tou-7** [comment]
@yuhan6665
能否添加过滤,将不符合条件过滤!
1. 参数,可以指定区域
2. 生成过滤后的文档(或生成完整文档,再次通过命令筛选不同结果文档 ps:有多个不同地区vps)
3. 在vps支持,后台运行
4. 在vps对符合条件的域名测试延时
5. 在vps过滤文档的域名(vps搜索的快,本地慢),在本地再运行多一次(以防域名在本地是不通的)
如有说的不对,请@yuhan6665多多原谅!
(vps,可以用垃圾小鸡,十来块一个月,就不当心搜索到本地ip遭到不好事情发生!)
(希望有其他贡献者定期,在GitHub分享搜索结果)
(还有一个大胆想法,将RealiTLScanner在GitHub的Actions运行,然后搜索结果返回到自己GitHub中!不知道是否可行呢)

**Comment by yuhan6665** [comment]
感谢反馈
1 可以加
2 3 命令行背景运行并定向输出即可
4 可以加

**Comment by yuhan6665** [comment]
对于第2条 v0.1.1 改为默认过滤不符合条件的服务器 -o 生成文档 results.txt

**Comment by yuhan6665** [comment]
Support IP CIDR and list now in latest version
