### ISSUE TITLE
erorr the target machine actively refused it.

### ISSUE THREAD

**Issue by haeydis** [XTLS/RealiTLScanner#11]
hi when i run windows app this error is appare
Reality TLS Scanner running: 127.0.0.1:443 start scan at : 2023-07-23T19:56:31+03:30
Dial failed: dial tcp 127.0.0.1:443: connectex: No connection could be made because the target machine actively refused it.

**Comment by ahenzen** [comment]
got the same probably you find a solution yet?

**Comment by yuhan6665** [comment]
You need to input an IP for scanning. See examples
