### ISSUE TITLE
Please fix your client

### ISSUE THREAD

**Issue by hoseinnikkhah** [XTLS/RealiTLScanner#13]
I've been getting this error on my windows machine recently while on my debian machine I don;t get it, can someone specify this error?
![image](https://github.com/XTLS/RealiTLScanner/assets/116885462/57501db2-101c-42ac-bf8e-c5ef574770d3)
Why this is happening?

**Comment by yuhan6665** [comment]
This is expected. Some of the CDN ip like 1.1.1.1 has many websites behind it. You need to pass in SNI for TLS connection to work.
They are candidate for Reality protocol.
