### ISSUE TITLE
HTTP Status, Allowed domains, Verbose output file

### ISSUE THREAD

**Issue by APT-ZERO** [XTLS/RealiTLScanner#18]
Hi,

Please add an option to show/save each feasible target's HTTP Status (when connected to IP without SNI)
Then we can know if we can use that domain as fallback of our reality or not

option to paste list of 'Allowed domains' for each domain like xray-core tls ping

ability to Parse ASN of each IP

option to make output file more detailed

Thank you.

**Comment by yuhan6665** [comment]
If you are saying there is a bug accepting a list. Please provide minimum list that you can reproduce the issue.

**Comment by yuhan6665** [comment]
I think the issue is that you can only use plain text file reliably
# Scan a list of targets from a file (targets should be divided by line break):
./RealiTLScanner -in in.txt
