### ISSUE TITLE
show error when wanna open this script

### ISSUE THREAD

**Issue by Anonpigo** [XTLS/RealiTLScanner#3]
hi my friend 
I wanna start RealiTLScanner  in win 10 but show error
I install go language but cant start  RealiTLScanner

**Comment by Anonpigo** [comment]
Dial failed:  dial tcp 127.0.0.215:443: connectex: No connection could be made because the target machine actively refused it.
show this error

**Comment by yuhan6665** [comment]
This is expected when you scan an address without tls server

**Comment by Anonpigo** [comment]
must import address in file and then scan ?

**Comment by yumeo-ch** [comment]
how do you use this tool ?
We need a simple guide on how to install it
