### ISSUE TITLE
辛苦问一下，推荐在本地运行什么意思？

### ISSUE THREAD

**Issue by lhbdhr** [XTLS/RealiTLScanner#4]
这里的本地和云端指的是什么呀？

意思是不推荐在VPS上运行？
按理说VPS运行这个程序的话，流量都没过墙为什么会被标记？
以及被标记什么？ 是会被墙标记成翻墙VPS吗？
以及被谁标记？被墙标记？还是因为这样的扫描是不被VPS厂商允许的，容易被VPS厂商标记？

**Comment by XCwosjw** [comment]
容易被VPS厂商标记。扫描在绝大部分VPS服务商的TOS里是明文禁止的

**Comment by lhbdhr** [comment]
这样啊，懂了。感谢。

**Comment by UjuiUjuMandan** [comment]
> 容易被VPS厂商标记。扫描在绝大部分VPS服务商的TOS里是明文禁止的

@Illustar0 Um, which ones? 

Many experiments on https://gfw.report use one or more VPS to massively scan or probe IP addresses.
