### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by AC-Lover** [XTLS/RealiTLScanner#9]
I want to scan but it gives me this error

![image](https://github.com/XTLS/RealiTLScanner/assets/49290111/d7866d47-e48b-402c-b3f9-1c1e4a199b2e)

Edition	`Windows 11 Pro`
Version	`21H2`
OS build	`22000.1880`
Experience	`Windows Feature Experience Pack 1000.22001.1000.0`

**Comment by Mahdad99** [comment]
same problem

**Comment by nickali2** [comment]
به جای گرفتن فایل اجرای ریپازیتوری رو دانلود کنید. فایل main.go رو توی vscode باز کنید. خط 35 لوکیشین رو بهجای شانگهای برابر تهران قرار بدید. مثل این:
`location, _ := time.LoadLocation("Asia/Tehran")`
بعد فایل رو ذخیره کنید و دستور go build رو اجرا کنید. یک فایل اجرایی ساخته میشه اونو با این دستور اجرا کنید. ضمنا برای اینکار باید go رو نصب کرده باشید.

**Comment by AC-Lover** [comment]
Thank you, I made the necessary changes and got the build, it was ok 

[RealiTLScanner_FixedVersion.zip](https://github.com/XTLS/RealiTLScanner/files/11446467/RealiTLScanner_FixedVersion.zip)


> به جای گرفتن فایل اجرای ریپازیتوری رو دانلود کنید. فایل main.go رو توی vscode باز کنید. خط 35 لوکیشین رو بهجای شانگهای برابر تهران قرار بدید. مثل این: `location, _ := time.LoadLocation("Asia/Tehran")` بعد فایل رو ذخیره کنید و دستور go build رو اجرا کنید. یک فایل اجرایی ساخته میشه اونو با این دستور اجرا کنید. ضمنا برای اینکار باید go رو نصب کرده باشید.
> 
> > I want to scan but it gives me this error
> > ![image](https://user-images.githubusercontent.com/49290111/237167210-d7866d47-e48b-402c-b3f9-1c1e4a199b2e.png)
> > Edition `Windows 11 Pro` Version `21H2` OS build `22000.1880` Experience `Windows Feature Experience Pack 1000.22001.1000.0`

**Comment by yuhan6665** [comment]
@AC-Lover if you can show your fix, more people will thank you for it :)

**Comment by AC-Lover** [comment]
> @AC-Lover if you can show your fix, more people will thank you for it :)

I also put inside the source zip file
But I will take pictures again

I changed line 35
`location, _ := time.LoadLocation("Asia/Shanghai")` => `location, _ := time.LoadLocation("Asia/Tehran")`

![image](https://github.com/XTLS/RealiTLScanner/assets/49290111/9a8121e6-d232-471d-b5c6-a68632eb2c0d)



In my country, the summer time zone was recently updated, I think it is because of the problem

**Comment by yuhan6665** [comment]
Hmm I see. I will try to make it generic like using UTC.

**Comment by yuhan6665** [comment]
Thanks for your report. Fixed in v0.1.2

**Comment by AC-Lover** [comment]
@yuhan6665 Hello, I have an idea for this project, can you send me your Telegram username so I can contact you?

**Comment by yuhan6665** [comment]
> @yuhan6665 Hello, I have an idea for this project, can you send me your Telegram username so I can contact you?

Yuhan6665
